import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/templates/Navbar";
import ParticlesBackground from "./components/templates/ParticlesBackground";
import { Toaster } from "react-hot-toast";
import { QueryProvider } from "@/utils/query";

const font = localFont({
  src: "../../public/fonts/BYekan/BYekan+ Bold.ttf",
  variable: "--font-BYekan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${font.variable}`}>
        <QueryProvider>
          <Navbar />
          <ParticlesBackground> {children}</ParticlesBackground>
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              style: {
                background: "#333",
                color: "#fff",
              },
            }}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
